[dag_settings]
dag_id = pipeline_with_config
schedule_interval = @daily

[customers_params]
force_recreate = False
datasets_dir = /opt/airflow/datasets
customer_filename = customers.csv
number_of_customers = 1000
age_range_min = 18
age_range_max = 65
items_list = Laptop, Mouse, Keyboard, Monitor, Phone, Desk Lamp
purchase_value_range_min = 10
purchase_value_range_max = 2000
total_value_mult_range_min = 1.5
total_value_mult_range_max = 10

stats_file_name = customers_stats.csv

[analysis_params]
target_item = Laptop
min_spend_threshold = 500
target_age_min = 25
target_age_max = 40
# # Minimum seniority in days
target_min_seniority = 30 
output_predictions_path = /opt/airflow/datasets/marketing_targets.csv



[params]

output_path = /data/processed/customers_cleaned.csv
batch_size = 1000
retry_count = 3
