import pandas as pd
from datetime import datetime
import wandb

def identify_marketing_targets(input_file, output_path, target_item, min_spend, age_min, age_max, min_seniority,
                               wandb_project = None, experiment_id="manual_run"):
    
    if wandb_project:
        print(f"Using wandb for logging... Experiment: {experiment_id}")
        # Initialize W&B Run
        run = wandb.init(
            project=wandb_project,
            job_type="prediction",
            name=f"age_{age_min}_{age_max}_seniority_{min_seniority}_spend_{min_spend}_{datetime.now().strftime('%H%M%S')}",
            config={
                "target_item": target_item,
                "min_spend": float(min_spend),
                "age_min": float(age_min),
                "age_max": float(age_max),
                "min_seniority": float(min_seniority),
                "experiment_id": experiment_id
            }
        )
    
    print("Running Targeting Logic with the following params values:")
    print(f"target_item = {target_item} ; min_spend = {min_spend} ; age_min = {age_min} ; age_max = {age_max} ; min_seniority = {min_seniority}")
    
    # Load the data generated by task 1
    df = pd.read_csv(input_file)
    df['customer_created_ts'] = pd.to_datetime(df['customer_created_ts'], errors='coerce')
    # Logic: 1 if they meet ALL criteria, else 0
    # 1. Did they buy the target item? (Checking the list string)
    # 2. Is their purchase value high enough?
    # 3. Are they in the age range?
    # 4. Does their seniority is high enough?
    
    # Calculate Seniority (Days since joined)
    # We use .dt.days to get a clean integer
    now = pd.Timestamp.now()
    df['seniority_days'] = (now - df['customer_created_ts']).dt.days
    
    # 
    df['is_high_value'] = (
        (df['last_purchase_items'].str.contains(target_item, na=False)) & 
        (df['total_value'] >= float(min_spend)) & 
        (df['customer_age'] >= int(age_min)) & 
        (df['customer_age'] <= int(age_max)) &
        (df['seniority_days'] >= int(min_seniority))
    ).astype(int)
    
    # Save the new dataset
    df.to_csv(output_path, index=False)
    

    
    # Calculate the 'Target Metric' for the logs
    num_targets = df['is_high_value'].sum()
    conversion_rate = (df['is_high_value'].sum() / len(df)) * 100
    print(f"Targeting Logic Applied (target_item = {target_item}, min_spend = {min_spend}, age_min = {age_min}, age_max = {age_max},\
          min_Seniority > {min_seniority} days).")

    print(f"Targeting Logic Applied. Found {num_targets} customers meeting criteria.")
    print(f"Target Metric (Conversion Rate): {conversion_rate}%")   
     
    ##### wandb logs:
    if wandb_project:
        wandb.log({
            "target_item": str(target_item),
            "min_spend": float(min_spend),
            "age_min": float(age_min),
            "age_max": float(age_max),
            "min_seniority": float(min_seniority),
            "target_count": num_targets,
            "conversion_rate": conversion_rate,
            "experiment_id": experiment_id,
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "total_customers": len(df)
        }) 
        # Log the output file as an Artifact
        try:
            artifact = wandb.Artifact(name="marketing_targets", type="dataset")
            artifact.add_file(output_path)
            run.log_artifact(artifact)
            print("artifact logged successfully")
        except:
            print("problem logging the artifact")
        print(f"W&B Run Complete. Target Metric: {conversion_rate}%")
        run.finish()
    
    return str(output_path)